package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/MicahParks/keyfunc/v3"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/cors"
	"github.com/golang-jwt/jwt/v5"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type App struct { DB *pgxpool.Pool; JWKS keyfunc.Keyfunc; Audience string }
type Product struct { ID string `json:"id"`; Name string `json:"name"`; Slug string `json:"slug"`; Description string `json:"description"`; ImageEmoji string `json:"imageEmoji"`; PriceCents int `json:"priceCents"`; OldPriceCents *int `json:"oldPriceCents"`; Stock int `json:"stock"`; Rating float64 `json:"rating"`; ReviewCount int `json:"reviewCount"`; SellerName string `json:"sellerName"`; CategorySlug string `json:"categorySlug"` }
type Category struct { ID string `json:"id"`; Name string `json:"name"`; Slug string `json:"slug"`; Icon string `json:"icon"` }
type UserProfile struct { ID string `json:"id"`; IdentitySubject string `json:"identitySubject"`; Email string `json:"email"`; Name string `json:"name"`; PictureURL string `json:"pictureUrl"`; Role string `json:"role"` }
type SyncProfileRequest struct { Email string `json:"email"`; Name string `json:"name"`; PictureURL string `json:"pictureUrl"` }
type AddCartItemRequest struct { ProductID string `json:"productId"`; Quantity int `json:"quantity"` }
type CartItem struct { ProductID string `json:"productId"`; Name string `json:"name"`; Slug string `json:"slug"`; ImageEmoji string `json:"imageEmoji"`; PriceCents int `json:"priceCents"`; Quantity int `json:"quantity"`; LineTotal int `json:"lineTotal"`; SellerName string `json:"sellerName"`; Rating float64 `json:"rating"`; ReviewCount int `json:"reviewCount"` }
type CartResponse struct { CartID string `json:"cartId"`; Items []CartItem `json:"items"`; ItemCount int `json:"itemCount"`; TotalCents int `json:"totalCents"` }
type OrderResponse struct { OrderID string `json:"orderId"`; Status string `json:"status"`; TotalCents int `json:"totalCents"`; Items []CartItem `json:"items"`; CreatedAt time.Time `json:"createdAt"` }
type SellerDashboard struct { SellerID string `json:"sellerId"`; SellerName string `json:"sellerName"`; ProductsActive int `json:"productsActive"`; StockTotal int `json:"stockTotal"`; ItemsSold int `json:"itemsSold"`; RevenueCents int `json:"revenueCents"`; OrdersCount int `json:"ordersCount"` }
type AdminDashboard struct { UsersCount int `json:"usersCount"`; SellersCount int `json:"sellersCount"`; ProductsCount int `json:"productsCount"`; OrdersCount int `json:"ordersCount"`; RevenueCents int `json:"revenueCents"`; StockTotal int `json:"stockTotal"` }
type Claims struct { Permissions []string `json:"permissions"`; Email string `json:"email"`; Name string `json:"name"`; Picture string `json:"picture"`; jwt.RegisteredClaims }

func main(){ctx:=context.Background(); port:=getenv("PORT","8080"); databaseURL:=getenv("DATABASE_URL","postgres://nexus:nexus_dev_password@localhost:5432/nexus_commerce?sslmode=disable"); frontendOrigin:=getenv("FRONTEND_ORIGIN","http://localhost:5173"); auth0Domain:=strings.TrimRight(os.Getenv("AUTH0_DOMAIN"),"/"); audience:=os.Getenv("AUTH0_AUDIENCE"); pool,err:=pgxpool.New(ctx,databaseURL); if err!=nil{log.Fatal(err)}; defer pool.Close(); if err:=pool.Ping(ctx);err!=nil{log.Fatal(err)}; var jwks keyfunc.Keyfunc; if auth0Domain!=""{jwks,err=keyfunc.NewDefaultCtx(ctx,[]string{fmt.Sprintf("%s/.well-known/jwks.json",auth0Domain)}); if err!=nil{log.Fatal(err)}}; app:=&App{DB:pool,JWKS:jwks,Audience:audience}; r:=chi.NewRouter(); r.Use(cors.Handler(cors.Options{AllowedOrigins:[]string{frontendOrigin},AllowedMethods:[]string{"GET","POST","PUT","DELETE","OPTIONS"},AllowedHeaders:[]string{"Accept","Authorization","Content-Type"},AllowCredentials:true,MaxAge:300})); r.Get("/health",func(w http.ResponseWriter,r *http.Request){writeJSON(w,http.StatusOK,map[string]any{"status":"ok","time":time.Now().UTC()})}); r.Get("/api/categories",app.listCategories); r.Get("/api/products",app.listProducts); r.Get("/api/products/{slug}",app.getProduct); r.Group(func(private chi.Router){private.Use(app.authMiddleware); private.Get("/api/me",app.me); private.Post("/api/profile/sync",app.syncProfile); private.Get("/api/cart",app.getCart); private.Post("/api/cart/items",app.addCartItem); private.Get("/api/orders",app.listOrders); private.Post("/api/orders",app.createOrder); private.Get("/api/seller/dashboard",app.sellerDashboard); private.Get("/api/seller/products",app.sellerProducts); private.Get("/api/seller/orders",app.sellerOrders); private.Get("/api/admin/dashboard",app.adminDashboard); private.Get("/api/admin/users",app.adminUsers); private.Get("/api/admin/sellers",app.adminSellers); private.Get("/api/admin/products",app.adminProducts); private.Get("/api/admin/orders",app.adminOrders)}); log.Printf("Nexus API listening on :%s",port); log.Fatal(http.ListenAndServe(":"+port,r))}

func (a *App) listCategories(w http.ResponseWriter,r *http.Request){rows,err:=a.DB.Query(r.Context(),`SELECT id,name,slug,icon FROM categories ORDER BY name`); if err!=nil{writeError(w,err);return}; defer rows.Close(); items:=[]Category{}; for rows.Next(){var c Category; if err:=rows.Scan(&c.ID,&c.Name,&c.Slug,&c.Icon);err!=nil{writeError(w,err);return}; items=append(items,c)}; writeJSON(w,http.StatusOK,items)}
func (a *App) listProducts(w http.ResponseWriter,r *http.Request){rows,err:=a.DB.Query(r.Context(),`SELECT p.id,p.name,p.slug,p.description,p.image_emoji,p.price_cents,p.old_price_cents,p.stock,p.rating,p.review_count,s.name,c.slug FROM products p JOIN sellers s ON s.id=p.seller_id JOIN categories c ON c.id=p.category_id WHERE ($1='' OR c.slug=$1) AND ($2='' OR p.name ILIKE '%' || $2 || '%') ORDER BY p.is_featured DESC,p.created_at DESC LIMIT 48`,r.URL.Query().Get("category"),strings.TrimSpace(r.URL.Query().Get("q"))); if err!=nil{writeError(w,err);return}; defer rows.Close(); products,err:=scanProducts(rows); if err!=nil{writeError(w,err);return}; writeJSON(w,http.StatusOK,products)}
func (a *App) getProduct(w http.ResponseWriter,r *http.Request){row:=a.DB.QueryRow(r.Context(),`SELECT p.id,p.name,p.slug,p.description,p.image_emoji,p.price_cents,p.old_price_cents,p.stock,p.rating,p.review_count,s.name,c.slug FROM products p JOIN sellers s ON s.id=p.seller_id JOIN categories c ON c.id=p.category_id WHERE p.slug=$1`,chi.URLParam(r,"slug")); var p Product; if err:=row.Scan(&p.ID,&p.Name,&p.Slug,&p.Description,&p.ImageEmoji,&p.PriceCents,&p.OldPriceCents,&p.Stock,&p.Rating,&p.ReviewCount,&p.SellerName,&p.CategorySlug);err!=nil{writeError(w,err);return}; writeJSON(w,http.StatusOK,p)}
func (a *App) me(w http.ResponseWriter,r *http.Request){claims:=r.Context().Value("claims").(*Claims); profile,err:=a.getProfileBySubject(r.Context(),claims.Subject); if err==nil{writeJSON(w,http.StatusOK,map[string]any{"subject":claims.Subject,"permissions":claims.Permissions,"profile":profile});return}; writeJSON(w,http.StatusOK,map[string]any{"subject":claims.Subject,"permissions":claims.Permissions})}
func (a *App) syncProfile(w http.ResponseWriter,r *http.Request){claims:=r.Context().Value("claims").(*Claims); var input SyncProfileRequest; _=json.NewDecoder(r.Body).Decode(&input); if input.Email==""{input.Email=claims.Email}; if input.Name==""{input.Name=claims.Name}; if input.PictureURL==""{input.PictureURL=claims.Picture}; if input.Email==""{input.Email=fmt.Sprintf("%s@nexus.local",strings.ReplaceAll(claims.Subject,"|","-"))}; row:=a.DB.QueryRow(r.Context(),`INSERT INTO user_profiles (identity_subject,email,name,picture_url,role) VALUES ($1,$2,$3,$4,COALESCE((SELECT role FROM user_profiles WHERE identity_subject=$1),'customer')) ON CONFLICT (identity_subject) DO UPDATE SET email=EXCLUDED.email,name=EXCLUDED.name,picture_url=EXCLUDED.picture_url,updated_at=now() RETURNING id,identity_subject,email,COALESCE(name,''),COALESCE(picture_url,''),role`,claims.Subject,input.Email,input.Name,input.PictureURL); var p UserProfile; if err:=row.Scan(&p.ID,&p.IdentitySubject,&p.Email,&p.Name,&p.PictureURL,&p.Role);err!=nil{writeError(w,err);return}; writeJSON(w,http.StatusOK,p)}
func (a *App) getProfileBySubject(ctx context.Context,subject string)(UserProfile,error){row:=a.DB.QueryRow(ctx,`SELECT id,identity_subject,email,COALESCE(name,''),COALESCE(picture_url,''),role FROM user_profiles WHERE identity_subject=$1`,subject); var p UserProfile; err:=row.Scan(&p.ID,&p.IdentitySubject,&p.Email,&p.Name,&p.PictureURL,&p.Role); return p,err}
func (a *App) getCart(w http.ResponseWriter,r *http.Request){claims:=r.Context().Value("claims").(*Claims); cartID,err:=a.getOrCreateOpenCart(r.Context(),claims.Subject); if err!=nil{writeError(w,err);return}; cart,err:=a.buildCartResponse(r.Context(),cartID); if err!=nil{writeError(w,err);return}; writeJSON(w,http.StatusOK,cart)}
func (a *App) addCartItem(w http.ResponseWriter,r *http.Request){claims:=r.Context().Value("claims").(*Claims); var input AddCartItemRequest; if err:=json.NewDecoder(r.Body).Decode(&input);err!=nil{writeError(w,err);return}; if input.ProductID==""{writeJSON(w,http.StatusBadRequest,map[string]string{"error":"productId is required"});return}; if input.Quantity<=0{input.Quantity=1}; if input.Quantity>99{input.Quantity=99}; cartID,err:=a.getOrCreateOpenCart(r.Context(),claims.Subject); if err!=nil{writeError(w,err);return}; _,err=a.DB.Exec(r.Context(),`INSERT INTO cart_items (cart_id,product_id,quantity) VALUES ($1,$2,$3) ON CONFLICT (cart_id,product_id) DO UPDATE SET quantity=cart_items.quantity+EXCLUDED.quantity`,cartID,input.ProductID,input.Quantity); if err!=nil{writeError(w,err);return}; cart,err:=a.buildCartResponse(r.Context(),cartID); if err!=nil{writeError(w,err);return}; writeJSON(w,http.StatusCreated,cart)}
func (a *App) getOrCreateOpenCart(ctx context.Context,customerRef string)(string,error){var id string; err:=a.DB.QueryRow(ctx,`SELECT id FROM carts WHERE customer_ref=$1 AND status='open' ORDER BY created_at DESC LIMIT 1`,customerRef).Scan(&id); if err==nil{return id,nil}; if !errors.Is(err,pgx.ErrNoRows){return "",err}; err=a.DB.QueryRow(ctx,`INSERT INTO carts (customer_ref,status) VALUES ($1,'open') RETURNING id`,customerRef).Scan(&id); return id,err}
func (a *App) buildCartResponse(ctx context.Context,cartID string)(CartResponse,error){rows,err:=a.DB.Query(ctx,`SELECT p.id,p.name,p.slug,p.image_emoji,p.price_cents,ci.quantity,s.name,p.rating,p.review_count FROM cart_items ci JOIN products p ON p.id=ci.product_id JOIN sellers s ON s.id=p.seller_id WHERE ci.cart_id=$1 ORDER BY p.name`,cartID); if err!=nil{return CartResponse{},err}; defer rows.Close(); cart:=CartResponse{CartID:cartID,Items:[]CartItem{}}; for rows.Next(){var item CartItem; if err:=rows.Scan(&item.ProductID,&item.Name,&item.Slug,&item.ImageEmoji,&item.PriceCents,&item.Quantity,&item.SellerName,&item.Rating,&item.ReviewCount);err!=nil{return CartResponse{},err}; item.LineTotal=item.PriceCents*item.Quantity; cart.TotalCents+=item.LineTotal; cart.ItemCount+=item.Quantity; cart.Items=append(cart.Items,item)}; return cart,rows.Err()}
func (a *App) listOrders(w http.ResponseWriter,r *http.Request){claims:=r.Context().Value("claims").(*Claims); rows,err:=a.DB.Query(r.Context(),`SELECT id,status,total_cents,created_at FROM orders WHERE customer_ref=$1 ORDER BY created_at DESC LIMIT 20`,claims.Subject); if err!=nil{writeError(w,err);return}; defer rows.Close(); orders:=[]OrderResponse{}; for rows.Next(){var order OrderResponse; if err:=rows.Scan(&order.OrderID,&order.Status,&order.TotalCents,&order.CreatedAt);err!=nil{writeError(w,err);return}; order.Items,err=a.getOrderItems(r.Context(),order.OrderID); if err!=nil{writeError(w,err);return}; orders=append(orders,order)}; writeJSON(w,http.StatusOK,orders)}
func (a *App) getOrderItems(ctx context.Context,orderID string)([]CartItem,error){rows,err:=a.DB.Query(ctx,`SELECT p.id,p.name,p.slug,p.image_emoji,oi.unit_price_cents,oi.quantity,s.name,p.rating,p.review_count FROM order_items oi JOIN products p ON p.id=oi.product_id JOIN sellers s ON s.id=oi.seller_id WHERE oi.order_id=$1 ORDER BY p.name`,orderID); if err!=nil{return nil,err}; defer rows.Close(); items:=[]CartItem{}; for rows.Next(){var item CartItem; if err:=rows.Scan(&item.ProductID,&item.Name,&item.Slug,&item.ImageEmoji,&item.PriceCents,&item.Quantity,&item.SellerName,&item.Rating,&item.ReviewCount);err!=nil{return nil,err}; item.LineTotal=item.PriceCents*item.Quantity; items=append(items,item)}; return items,rows.Err()}
func (a *App) createOrder(w http.ResponseWriter,r *http.Request){claims:=r.Context().Value("claims").(*Claims); ctx:=r.Context(); cartID,err:=a.getOrCreateOpenCart(ctx,claims.Subject); if err!=nil{writeError(w,err);return}; cart,err:=a.buildCartResponse(ctx,cartID); if err!=nil{writeError(w,err);return}; if cart.ItemCount==0{writeJSON(w,http.StatusBadRequest,map[string]string{"error":"cart is empty"});return}; tx,err:=a.DB.Begin(ctx); if err!=nil{writeError(w,err);return}; defer tx.Rollback(ctx); var order OrderResponse; err=tx.QueryRow(ctx,`INSERT INTO orders (customer_ref,total_cents,status) VALUES ($1,$2,'pending') RETURNING id,status,total_cents,created_at`,claims.Subject,cart.TotalCents).Scan(&order.OrderID,&order.Status,&order.TotalCents,&order.CreatedAt); if err!=nil{writeError(w,err);return}; _,err=tx.Exec(ctx,`INSERT INTO order_items (order_id,product_id,seller_id,quantity,unit_price_cents) SELECT $1,p.id,p.seller_id,ci.quantity,p.price_cents FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.cart_id=$2`,order.OrderID,cartID); if err!=nil{writeError(w,err);return}; _,err=tx.Exec(ctx,`UPDATE carts SET status='converted',updated_at=now() WHERE id=$1`,cartID); if err!=nil{writeError(w,err);return}; if err:=tx.Commit(ctx);err!=nil{writeError(w,err);return}; order.Items=cart.Items; writeJSON(w,http.StatusCreated,order)}
func (a *App) sellerDashboard(w http.ResponseWriter,r *http.Request){sellerID,sellerName,ok:=a.resolveSeller(w,r); if !ok{return}; var d SellerDashboard; d.SellerID=sellerID; d.SellerName=sellerName; _=a.DB.QueryRow(r.Context(),`SELECT COUNT(*),COALESCE(SUM(stock),0) FROM products WHERE seller_id=$1`,sellerID).Scan(&d.ProductsActive,&d.StockTotal); _=a.DB.QueryRow(r.Context(),`SELECT COALESCE(SUM(oi.quantity),0),COALESCE(SUM(oi.quantity*oi.unit_price_cents),0),COUNT(DISTINCT oi.order_id) FROM order_items oi WHERE oi.seller_id=$1`,sellerID).Scan(&d.ItemsSold,&d.RevenueCents,&d.OrdersCount); writeJSON(w,http.StatusOK,d)}
func (a *App) sellerProducts(w http.ResponseWriter,r *http.Request){sellerID,_,ok:=a.resolveSeller(w,r); if !ok{return}; rows,err:=a.DB.Query(r.Context(),`SELECT p.id,p.name,p.slug,p.description,p.image_emoji,p.price_cents,p.old_price_cents,p.stock,p.rating,p.review_count,s.name,c.slug FROM products p JOIN sellers s ON s.id=p.seller_id JOIN categories c ON c.id=p.category_id WHERE p.seller_id=$1 ORDER BY p.created_at DESC`,sellerID); if err!=nil{writeError(w,err);return}; defer rows.Close(); products,err:=scanProducts(rows); if err!=nil{writeError(w,err);return}; writeJSON(w,http.StatusOK,products)}
func (a *App) sellerOrders(w http.ResponseWriter,r *http.Request){sellerID,_,ok:=a.resolveSeller(w,r); if !ok{return}; rows,err:=a.DB.Query(r.Context(),`SELECT DISTINCT o.id,o.status,o.total_cents,o.created_at FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE oi.seller_id=$1 ORDER BY o.created_at DESC LIMIT 30`,sellerID); if err!=nil{writeError(w,err);return}; defer rows.Close(); orders:=[]OrderResponse{}; for rows.Next(){var order OrderResponse; if err:=rows.Scan(&order.OrderID,&order.Status,&order.TotalCents,&order.CreatedAt);err!=nil{writeError(w,err);return}; order.Items,err=a.getSellerOrderItems(r.Context(),order.OrderID,sellerID); if err!=nil{writeError(w,err);return}; orders=append(orders,order)}; writeJSON(w,http.StatusOK,orders)}
func (a *App) getSellerOrderItems(ctx context.Context,orderID,sellerID string)([]CartItem,error){rows,err:=a.DB.Query(ctx,`SELECT p.id,p.name,p.slug,p.image_emoji,oi.unit_price_cents,oi.quantity,s.name,p.rating,p.review_count FROM order_items oi JOIN products p ON p.id=oi.product_id JOIN sellers s ON s.id=oi.seller_id WHERE oi.order_id=$1 AND oi.seller_id=$2 ORDER BY p.name`,orderID,sellerID); if err!=nil{return nil,err}; defer rows.Close(); items:=[]CartItem{}; for rows.Next(){var item CartItem; if err:=rows.Scan(&item.ProductID,&item.Name,&item.Slug,&item.ImageEmoji,&item.PriceCents,&item.Quantity,&item.SellerName,&item.Rating,&item.ReviewCount);err!=nil{return nil,err}; item.LineTotal=item.PriceCents*item.Quantity; items=append(items,item)}; return items,rows.Err()}
func (a *App) resolveSeller(w http.ResponseWriter,r *http.Request)(string,string,bool){claims:=r.Context().Value("claims").(*Claims); profile,_:=a.getProfileBySubject(r.Context(),claims.Subject); if profile.Role!="seller"&&profile.Role!="admin"{writeJSON(w,http.StatusForbidden,map[string]string{"error":"seller role required"}); return "","",false}; var id,name string; err:=a.DB.QueryRow(r.Context(),`SELECT id,name FROM sellers WHERE owner_subject=$1 LIMIT 1`,claims.Subject).Scan(&id,&name); if errors.Is(err,pgx.ErrNoRows){err=a.DB.QueryRow(r.Context(),`SELECT id,name FROM sellers ORDER BY created_at LIMIT 1`).Scan(&id,&name)}; if err!=nil{writeError(w,err);return "","",false}; return id,name,true}
func (a *App) requireAdmin(w http.ResponseWriter,r *http.Request) bool{claims:=r.Context().Value("claims").(*Claims); profile,err:=a.getProfileBySubject(r.Context(),claims.Subject); if err!=nil||profile.Role!="admin"{writeJSON(w,http.StatusForbidden,map[string]string{"error":"admin role required"}); return false}; return true}
func (a *App) adminDashboard(w http.ResponseWriter,r *http.Request){if !a.requireAdmin(w,r){return}; var d AdminDashboard; _=a.DB.QueryRow(r.Context(),`SELECT COUNT(*) FROM user_profiles`).Scan(&d.UsersCount); _=a.DB.QueryRow(r.Context(),`SELECT COUNT(*) FROM sellers`).Scan(&d.SellersCount); _=a.DB.QueryRow(r.Context(),`SELECT COUNT(*),COALESCE(SUM(stock),0) FROM products`).Scan(&d.ProductsCount,&d.StockTotal); _=a.DB.QueryRow(r.Context(),`SELECT COUNT(*),COALESCE(SUM(total_cents),0) FROM orders`).Scan(&d.OrdersCount,&d.RevenueCents); writeJSON(w,http.StatusOK,d)}
func (a *App) adminUsers(w http.ResponseWriter,r *http.Request){if !a.requireAdmin(w,r){return}; rows,err:=a.DB.Query(r.Context(),`SELECT id,identity_subject,email,COALESCE(name,''),COALESCE(picture_url,''),role FROM user_profiles ORDER BY created_at DESC LIMIT 50`); if err!=nil{writeError(w,err);return}; defer rows.Close(); users:=[]UserProfile{}; for rows.Next(){var u UserProfile; if err:=rows.Scan(&u.ID,&u.IdentitySubject,&u.Email,&u.Name,&u.PictureURL,&u.Role);err!=nil{writeError(w,err);return}; users=append(users,u)}; writeJSON(w,http.StatusOK,users)}
func (a *App) adminSellers(w http.ResponseWriter,r *http.Request){if !a.requireAdmin(w,r){return}; rows,err:=a.DB.Query(r.Context(),`SELECT id,name,slug,status,COALESCE(owner_subject,'') FROM sellers ORDER BY created_at DESC LIMIT 50`); if err!=nil{writeError(w,err);return}; defer rows.Close(); items:=[]map[string]any{}; for rows.Next(){var id,name,slug,status,owner string; if err:=rows.Scan(&id,&name,&slug,&status,&owner);err!=nil{writeError(w,err);return}; items=append(items,map[string]any{"id":id,"name":name,"slug":slug,"status":status,"ownerSubject":owner})}; writeJSON(w,http.StatusOK,items)}
func (a *App) adminProducts(w http.ResponseWriter,r *http.Request){if !a.requireAdmin(w,r){return}; a.listProducts(w,r)}
func (a *App) adminOrders(w http.ResponseWriter,r *http.Request){if !a.requireAdmin(w,r){return}; rows,err:=a.DB.Query(r.Context(),`SELECT id,status,total_cents,created_at FROM orders ORDER BY created_at DESC LIMIT 50`); if err!=nil{writeError(w,err);return}; defer rows.Close(); orders:=[]OrderResponse{}; for rows.Next(){var order OrderResponse; if err:=rows.Scan(&order.OrderID,&order.Status,&order.TotalCents,&order.CreatedAt);err!=nil{writeError(w,err);return}; order.Items,err=a.getOrderItems(r.Context(),order.OrderID); if err!=nil{writeError(w,err);return}; orders=append(orders,order)}; writeJSON(w,http.StatusOK,orders)}
func (a *App) authMiddleware(next http.Handler) http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){if a.JWKS==nil||a.Audience==""{writeJSON(w,http.StatusServiceUnavailable,map[string]string{"error":"auth0 not configured"});return}; parts:=strings.Split(r.Header.Get("Authorization")," "); if len(parts)!=2||!strings.EqualFold(parts[0],"Bearer"){writeJSON(w,http.StatusUnauthorized,map[string]string{"error":"missing bearer token"});return}; claims:=&Claims{}; token,err:=jwt.ParseWithClaims(parts[1],claims,a.JWKS.Keyfunc); if err!=nil||!token.Valid{writeJSON(w,http.StatusUnauthorized,map[string]string{"error":"invalid token"});return}; if !claims.VerifyAudience(a.Audience,true){writeJSON(w,http.StatusUnauthorized,map[string]string{"error":"invalid audience"});return}; next.ServeHTTP(w,r.WithContext(context.WithValue(r.Context(),"claims",claims)))})}
type productRows interface{Next()bool; Scan(dest ...any)error; Err()error}
func scanProducts(rows productRows)([]Product,error){items:=[]Product{}; for rows.Next(){var p Product; if err:=rows.Scan(&p.ID,&p.Name,&p.Slug,&p.Description,&p.ImageEmoji,&p.PriceCents,&p.OldPriceCents,&p.Stock,&p.Rating,&p.ReviewCount,&p.SellerName,&p.CategorySlug);err!=nil{return nil,err}; items=append(items,p)}; return items,rows.Err()}
func getenv(key string,fallback string)string{value:=os.Getenv(key); if value==""{return fallback}; return value}
func writeJSON(w http.ResponseWriter,status int,payload any){w.Header().Set("Content-Type","application/json"); w.WriteHeader(status); _=json.NewEncoder(w).Encode(payload)}
func writeError(w http.ResponseWriter,err error){status:=http.StatusInternalServerError; if errors.Is(err,context.Canceled){status=http.StatusRequestTimeout}; writeJSON(w,status,map[string]string{"error":err.Error()})}
